# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_issues": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://retroam.github.io/gitviz/"

git_url = "https://github.com/retroam/gitviz/tree/main/"

def custom_doc_links(name): return None
