# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['get_issues']

# Cell
def get_issues(name):
    """Requests issues from GitHub API and writes to CSV file."""
    requests.adapters.DEFAULT_RETRIES = 5
    url = 'https://api.github.com/repos/{}/issues?state={}'.format(name, state)
    results = []
    r = requests.get(url, auth=auth)
    #print(url);

    jsonfilename = '{}-issues.json'.format(name.replace('/', '-'))
    with open(jsonfilename, 'w') as jsonfile:
        results.extend(r.json())

        # Multiple requests are required if response is paged
        if 'link' in r.headers:
            pages = {rel[6:-1]: url[url.index('<')+1:-1] for url, rel in
                     (link.split(';') for link in
                      r.headers['link'].split(','))}
            while 'last' in pages and 'next' in pages:

                pages = {rel[6:-1]: url[url.index('<')+1:-1] for url, rel in
                         (link.split(';') for link in
                          r.headers['link'].split(','))}
                r = requests.get(pages['next'], auth=auth)
                results.extend(r.json())

                if pages['next'] == pages['last']:
                    json.dump(results, jsonfile,ensure_ascii=False)
                    break
    return jsonfilename